---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:9090
    description: Generated server url
paths:
  "/updateproduct":
    put:
      tags:
        - product-controller
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Product"
            examples:
              200_UPDATE:
                value:
                  {
                    "cost": "100 $",
                    "name": "Artificial Lamp",
                    "id": 1
                  }
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Product"
              examples:
                200_UPDATE:
                  value:
  "/addProduct":
    post:
      tags:
        - product-controller
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Product"
            examples:
              200_ADD:
                value:
                  {
                    "cost": "300 $",
                    "name": "Wooden Sofa",
                    "id": 1
                  }
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Product"
              examples:
                200_ADD:
                  value:

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int32
          nullable: true
        name:
          type: string
          nullable: true
        cost:
          type: string
          nullable: true

