---
openapi: 3.0.1
info:
  title: Products API
  version: v1
paths:
  "/updateProduct":
    put:
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Product"
            examples:
              200_UPDATE:
                value:
                  {
                    "cost": 100,
                    "name": "Artificial Lamp",
                    "id": 1
                  }
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Product"
              examples:
                200_UPDATE:
                  value:
  "/addProduct":
    post:
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Product"
            examples:
              200_ADD:
                value:
                  {
                    "cost": 300,
                    "name": "Wooden Sofa",
                    "id": 1
                  }
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Product"
              examples:
                200_ADD:
                  value:

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          nullable: true
        name:
          type: string
          nullable: true
        cost:
          type: integer
          nullable: true

